SELECT
  COUNTRY,
  TITLE,
  CHANNELTITLE,
  VIEW_COUNT,
  RK
FROM (
  SELECT
    COUNTRY,
    TITLE,
    CHANNELTITLE,
    VIEW_COUNT,
    ROW_NUMBER() OVER (PARTITION BY COUNTRY ORDER BY VIEW_COUNT DESC) AS RK
  FROM table_youtube_final
  WHERE TRENDING_DATE = '2021-10-17'
    AND CATEGORY_TITLE = 'Sports'
) RANKED 
WHERE RK <= 3
ORDER BY COUNTRY, RK
;


