WITH CTE AS (
  SELECT
    COUNTRY,
    DATE_TRUNC('MONTH', TRENDING_DATE) AS year_month,
    TITLE,
    CHANNELTITLE,
    CATEGORY_TITLE,
    VIEW_COUNT,
    (LIKES::FLOAT / VIEW_COUNT * 100)::NUMERIC(10, 2) AS likes_ratio,
    ROW_NUMBER() OVER (PARTITION BY COUNTRY, DATE_TRUNC('MONTH', TRENDING_DATE) ORDER BY VIEW_COUNT DESC) AS rn
  FROM table_youtube_final
)
SELECT
  COUNTRY,
  year_month,
  TITLE,
  CHANNELTITLE,
  CATEGORY_TITLE,
  VIEW_COUNT,
  likes_ratio
FROM CTE
WHERE rn = 1
ORDER BY year_month, COUNTRY;